// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyDjzCu8ALBMH_UQh36W8bi1_TwSG9ga3lo',
      appId: '1:404433977247:web:8952427bd66ebfeba847aa',
      messagingSenderId: '404433977247',
      projectId: 'realtimeflutter-c5c86',
      authDomain: 'realtimeflutter-c5c86.firebaseapp.com',
      storageBucket: 'realtimeflutter-c5c86.appspot.com',
      measurementId: 'G-JP4ZG0FC3H',
      databaseURL:
          'https://realtimeflutter-c5c86-default-rtdb.firebaseio.com/');

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjAXAko2V6RwKdyH8LowFw1FyDVnPlFZs',
    appId: '1:404433977247:android:a972ec1a58111be4a847aa',
    messagingSenderId: '404433977247',
    projectId: 'realtimeflutter-c5c86',
    storageBucket: 'realtimeflutter-c5c86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8ZyDJh74VcM4OStpFnkZbsoVRQJb9pP4',
    appId: '1:404433977247:ios:66a576e985a61d32a847aa',
    messagingSenderId: '404433977247',
    projectId: 'realtimeflutter-c5c86',
    storageBucket: 'realtimeflutter-c5c86.appspot.com',
    iosBundleId: 'com.example.flutterrealtimedatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8ZyDJh74VcM4OStpFnkZbsoVRQJb9pP4',
    appId: '1:404433977247:ios:66a576e985a61d32a847aa',
    messagingSenderId: '404433977247',
    projectId: 'realtimeflutter-c5c86',
    storageBucket: 'realtimeflutter-c5c86.appspot.com',
    iosBundleId: 'com.example.flutterrealtimedatabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjzCu8ALBMH_UQh36W8bi1_TwSG9ga3lo',
    appId: '1:404433977247:web:94f0fe27cfa2645fa847aa',
    messagingSenderId: '404433977247',
    projectId: 'realtimeflutter-c5c86',
    authDomain: 'realtimeflutter-c5c86.firebaseapp.com',
    storageBucket: 'realtimeflutter-c5c86.appspot.com',
    measurementId: 'G-JQ4VVB7HCL',
  );
}
